import 'package:flutter/material.dart';
import 'api.dart';
import 'models.dart';
import 'mobile_screens.dart';
import 'mobile_management.dart';

void main() => runApp(const HydroSyncApp());

class HydroSyncApp extends StatefulWidget { const HydroSyncApp({super.key}); @override State<HydroSyncApp> createState()=>_HydroSyncAppState(); }
class _HydroSyncAppState extends State<HydroSyncApp>{final api=ApiClient();SessionUser?user;bool loading=true;@override void initState(){super.initState();boot();}Future<void>boot()async{if(await api.isLoggedIn())user=await api.session();if(mounted)setState(()=>loading=false);}@override Widget build(BuildContext context){Widget home;if(loading){home=const Scaffold(body:Center(child:CircularProgressIndicator()));}else if(user==null){home=LoginPage(api:api,onLogin:(u)=>setState(()=>user=u));}else{home=HomePage(api:api,user:user!,onLogout:()=>setState(()=>user=null));}return MaterialApp(debugShowCheckedModeBanner:false,title:'Municipal HydroSync',theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:Colors.blue),useMaterial3:true),home:home);}}

class LoginPage extends StatefulWidget{final ApiClient api;final void Function(SessionUser)onLogin;const LoginPage({super.key,required this.api,required this.onLogin});@override State<LoginPage>createState()=>_LoginPageState();}
class _LoginPageState extends State<LoginPage>{final email=TextEditingController(),password=TextEditingController();bool busy=false;String?error;@override void dispose(){email.dispose();password.dispose();super.dispose();}Future<void>submit()async{FocusScope.of(context).unfocus();setState((){busy=true;error=null;});try{final d=await widget.api.login(email.text.trim(),password.text);if(mounted)widget.onLogin(SessionUser.fromJson(d['user']));}catch(e){if(mounted)setState(()=>error='$e');}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.water_drop,size:60),const SizedBox(height:10),const Text('Municipal HydroSync',style:TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const Text('نظام العمليات الميدانية للمياه'),const SizedBox(height:24),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'البريد الإلكتروني',prefixIcon:Icon(Icons.email))),const SizedBox(height:12),TextField(controller:password,obscureText:true,onSubmitted:(_)=>busy?null:submit(),decoration:const InputDecoration(labelText:'كلمة المرور',prefixIcon:Icon(Icons.lock))),if(error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Align(alignment:Alignment.centerRight,child:Text(error!,style:const TextStyle(color:Colors.red)))),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:busy?null:submit,child:busy?const SizedBox(width:20,height:20,child:CircularProgressIndicator()):const Text('تسجيل الدخول')))]))))))));}

class HomePage extends StatefulWidget{final ApiClient api;final SessionUser user;final VoidCallback onLogout;const HomePage({super.key,required this.api,required this.user,required this.onLogout});@override State<HomePage>createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{int tab=0;int pending=0;late final List<Widget> pages;@override void initState(){super.initState();pages=<Widget>[Dashboard(api:widget.api),ManagedListPage(api:widget.api,complaints:true),ManagedListPage(api:widget.api,complaints:false),MapPage(api:widget.api),ProfilePage(user:widget.user,api:widget.api,onLogout:widget.onLogout)];sync();}Future<void>sync()async{try{final n=await widget.api.syncPending();final c=await widget.api.pendingCount();if(mounted){setState(()=>pending=c);if(n>0)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تمت مزامنة $n عملية')));}}catch(_){}}@override Widget build(BuildContext c){return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('Municipal HydroSync'),actions:[if(pending>0)Padding(padding:const EdgeInsets.all(12),child:Badge(label:Text('$pending'),child:const Icon(Icons.sync))),IconButton(onPressed:sync,icon:const Icon(Icons.sync))]),body:IndexedStack(index:tab,children:pages),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.report),label:'الشكاوى'),NavigationDestination(icon:Icon(Icons.engineering),label:'المهام'),NavigationDestination(icon:Icon(Icons.map),label:'الخريطة'),NavigationDestination(icon:Icon(Icons.person),label:'حسابي')])));}}

class Dashboard extends StatefulWidget{final ApiClient api;const Dashboard({super.key,required this.api});@override State<Dashboard>createState()=>_DashboardState();}
class _DashboardState extends State<Dashboard>{Map<String,dynamic>?data;@override void initState(){super.initState();load();}Future<void>load()async{try{final x=await widget.api.summary();if(mounted)setState(()=>data=x);}catch(_){}}@override Widget build(BuildContext c){if(data==null)return const Center(child:CircularProgressIndicator());final entries=data!.entries.where((e)=>e.value is num).toList();return RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[const Text('ملخص العمليات',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:12),Wrap(spacing:12,runSpacing:12,children:entries.map((e)=>SizedBox(width:165,child:Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${e.value}',style:const TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:5),Text(e.key)]))))).toList())]));}}
