import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'api.dart';
import 'models.dart';

class ListPage extends StatefulWidget{final ApiClient api;final String endpoint,title;final IconData icon;const ListPage({super.key,required this.api,required this.endpoint,required this.title,required this.icon});@override State<ListPage> createState()=>_ListPageState();}
class _ListPageState extends State<ListPage>{ApiList? data;@override void initState(){super.initState();load();}Future<void>load()async{try{final x=await widget.api.list(widget.endpoint);if(mounted)setState(()=>data=x);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}@override Widget build(BuildContext c)=>RefreshIndicator(onRefresh:load,child:data==null?const Center(child:CircularProgressIndicator()):ListView.builder(itemCount:data!.items.length,itemBuilder:(c,i){final m=data!.items[i];return Card(margin:const EdgeInsets.symmetric(horizontal:12,vertical:5),child:ListTile(leading:Icon(widget.icon),title:Text('\${m['title']??m['complaint_number']??m['work_order_number']??'-'}'),subtitle:Text('\${m['status']??'-'} • \${m['priority']??'-'}\n\${m['description']??''}'),isThreeLine:true));}));}

class MapPage extends StatefulWidget{final ApiClient api;const MapPage({super.key,required this.api});@override State<MapPage> createState()=>_MapPageState();}
class _MapPageState extends State<MapPage>{Map<String,dynamic>? d;@override void initState(){super.initState();load();}Future<void>load()async{try{final x=await widget.api.operationalMap();if(mounted)setState(()=>d=x);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}@override Widget build(BuildContext c){final markers=<Marker>[];for(final raw in (d?['complaints'] as List? ?? [])){final m=Map<String,dynamic>.from(raw);final a=(m['latitude'] as num?)?.toDouble(),b=(m['longitude'] as num?)?.toDouble();if(a!=null&&b!=null)markers.add(Marker(point:LatLng(a,b),width:45,height:45,child:const Icon(Icons.report_problem,color:Colors.red,size:34)));}for(final raw in (d?['work_orders'] as List? ?? [])){final m=Map<String,dynamic>.from(raw);final a=(m['latitude'] as num?)?.toDouble(),b=(m['longitude'] as num?)?.toDouble();if(a!=null&&b!=null)markers.add(Marker(point:LatLng(a,b),width:45,height:45,child:const Icon(Icons.engineering,color:Colors.orange,size:34)));}return FlutterMap(options:const MapOptions(initialCenter:LatLng(31.52,34.45),initialZoom:10),children:[TileLayer(urlTemplate:'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',subdomains:['a','b','c']),MarkerLayer(markers:markers)]);}}

class ProfilePage extends StatelessWidget{final SessionUser user;final ApiClient api;final VoidCallback onLogout;const ProfilePage({super.key,required this.user,required this.api,required this.onLogout});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(user.name),subtitle:Text(user.email))),Card(child:ListTile(title:const Text('الصلاحيات'),subtitle:Text(user.permissions.join('، ')))),const SizedBox(height:20),FilledButton.tonalIcon(onPressed:()async{await api.logout();onLogout();},icon:const Icon(Icons.logout),label:const Text('تسجيل الخروج'))]);}
